// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQCpWWwpxm1t6wruP22VI2RKKDlYPc7I',
    appId: '1:871129938001:web:46cec0df9ed02b7d476070',
    messagingSenderId: '871129938001',
    projectId: 'diu-food-hub',
    authDomain: 'diu-food-hub.firebaseapp.com',
    storageBucket: 'diu-food-hub.appspot.com',
    measurementId: 'G-WEXN4T7B35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtqudlz-abMkOYKrYo9t38r__BPeI6qa8',
    appId: '1:871129938001:android:63867e686933bb59476070',
    messagingSenderId: '871129938001',
    projectId: 'diu-food-hub',
    storageBucket: 'diu-food-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQmReBab8PSif8vw0xv-cUFQAEFMeZCo',
    appId: '1:871129938001:ios:6f310f14550fab80476070',
    messagingSenderId: '871129938001',
    projectId: 'diu-food-hub',
    storageBucket: 'diu-food-hub.appspot.com',
    iosBundleId: 'com.example.foodhubUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQmReBab8PSif8vw0xv-cUFQAEFMeZCo',
    appId: '1:871129938001:ios:2a835085e9302b05476070',
    messagingSenderId: '871129938001',
    projectId: 'diu-food-hub',
    storageBucket: 'diu-food-hub.appspot.com',
    iosBundleId: 'com.example.foodhubUserApp.RunnerTests',
  );
}
